"""Trusted Blender helper. Not generated by Grok."""
from __future__ import annotations
import bpy
from typing import Iterable

ALLOWED_ELEMENT_PREFIX = "element_"
ALLOWED_PROPERTY_KEYS = {
    "aidle_module_id","aidle_physical_profile_id","aidle_elements",
    "aidle_physics_modules","aidle_reaction_allowlist",
    "aidle_performance_class","aidle_catalog_version"
}

def assign_aidle_metadata(obj: bpy.types.Object, module_id: str,
    physical_profile_id: str | None, elements: Iterable[str],
    physics_modules: Iterable[str], reaction_allowlist: Iterable[str],
    performance_class: str, catalog_version: str = "1.0") -> None:
    obj["aidle_module_id"] = module_id
    obj["aidle_physical_profile_id"] = physical_profile_id or ""
    obj["aidle_elements"] = sorted({x for x in elements if x.startswith(ALLOWED_ELEMENT_PREFIX)})
    obj["aidle_physics_modules"] = sorted(set(physics_modules))
    obj["aidle_reaction_allowlist"] = sorted(set(reaction_allowlist))
    obj["aidle_performance_class"] = performance_class
    obj["aidle_catalog_version"] = catalog_version

def validate_no_unknown_aidle_properties(obj: bpy.types.Object) -> list[str]:
    return [f"{obj.name}: unknown property {key}" for key in obj.keys()
            if key.startswith("aidle_") and key not in ALLOWED_PROPERTY_KEYS]
